---

#  - include: ubuntu14.04-ansible-base.yml

  # ubuntu with oraclexe base image
  - file: path=/tmp/ubuntu state=directory

  - name: copy docker files
    copy: src={{item}} dest=/tmp/ubuntu
    with_items:
        - Dockerfile
        - site.yml
        - start.sh

#  - name: copy ansible-oraclexe role
#    copy: src="ansible-oraclexe" dest=/tmp/ubuntu

  - name: copy oracle files
    copy: src="oracle-xe-{{oracle_xe_version}}.x86_64.rpm" dest=/tmp/ubuntu

  - apt: name=git state=present
    when: ansible_os_family == "Debian"

  - yum: name=git state=present
    when: ansible_os_family == "RedHat"

  - shell: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

  - name: copy git module
    git: repo=https://github.com/fupelaqu/ansible-oraclexe.git dest=/tmp/ubuntu/roles/ansible-oraclexe

  - name: build ubuntu with oraclexe
    docker_image: path="/tmp/ubuntu"
                  name="ubuntu14.04-oraclexe"
                  state=present
                  tag="{{oracle_xe_version}}"
