---

#  - include: centos7-ansible-base.yml

  - include: oracle-xe-swap.yml

  # centos with oraclexe base image
  - file: path=/tmp/centos state=directory

  - name: copy docker files
    copy: src={{item}} dest=/tmp/centos
    with_items:
        - Dockerfile
        - site.yml
        - start.sh

#  - name: copy ansible-oraclexe role
#    copy: src="ansible-oraclexe" dest=/tmp/centos

  - name: copy oracle files
    copy: src="oracle-xe-{{oracle_xe_version}}.x86_64.rpm" dest=/tmp/centos

  - apt: name=git state=present
    when: ansible_os_family == "Debian"

  - yum: name=git state=present
    when: ansible_os_family == "RedHat"

  - shell: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

  - name: copy git module
    git: repo=https://github.com/fupelaqu/ansible-oraclexe.git dest=/tmp/centos/roles/ansible-oraclexe force=yes

  - name: build centos with oraclexe
    docker_image: path="/tmp/centos"
                  name="centos7-oraclexe"
                  state=present
                  tag="{{oracle_xe_version}}"
